### ISSUE TITLE
Returns wrong version when Chrome is updated but have not restarted yet

### ISSUE THREAD

**Issue by XcantloadX** [hasansezertasan/chrome-version#20]
Chrome version is 124.0.6367.202 according to chrome://settings/help page
![image](https://github.com/hasansezertasan/chrome-version/assets/25605245/dcf5fce0-1ff1-4210-9987-3f3e100e3be0)

Registry query output says it's 125.0.6422.61
```
C:\Users\ZhouXiaokang>reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome"

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
    DisplayName    REG_SZ    Google Chrome
    UninstallString    REG_SZ    "C:\Program Files\Google\Chrome\Application\125.0.6422.61\Installer\setup.exe" --uninstall --channel=stable --system-level --verbose-logging
    InstallLocation    REG_SZ    C:\Program Files\Google\Chrome\Application
    DisplayIcon    REG_SZ    C:\Program Files\Google\Chrome\Application\chrome.exe,0
    NoModify    REG_DWORD    0x1
    NoRepair    REG_DWORD    0x1
    Publisher    REG_SZ    Google LLC
    Version    REG_SZ    125.0.6422.61
    DisplayVersion    REG_SZ    125.0.6422.61
    InstallDate    REG_SZ    20240516
    VersionMajor    REG_DWORD    0x1916
    VersionMinor    REG_DWORD    0x3d
```

chrome.exe file says it's 124.0.6367.202:
![image](https://github.com/hasansezertasan/chrome-version/assets/25605245/b41e36f5-6208-45ef-a137-ea438da07c69)

The easiest way to fix this seems to be check chrome.exe file first instead of registry key.

**Comment by hasansezertasan** [comment]
Thanks for reporting 😇

> The easiest way to fix this seems to be check chrome.exe file first instead of registry key.

Are you sure it's not only on your system? I checked on my Windows 10 22H2 19045.4291 and it all looks good. I just updated chrome, I couldn't reproduce the problem.

**Comment by XcantloadX** [comment]
Solved by restart Windows。
