### ISSUE TITLE
Readme credit update

### ISSUE THREAD

**Issue by primaryobjects** [hasansezertasan/chrome-version#7]
This is fantastic and thank you for creating a package for chrome-version!

Would you be able to please update the readme Disclaimer section as below? Hopefully this shortens the disclaimer text to be simpler.

Based on [chrome-version](https://gist.github.com/primaryobjects/d5346bf7a173dbded1a70375ff7461b4) by [Kory Becker](https://github.com/primaryobjects).

This package provides a CLI wrapper for the original project. All credit reserved to the author of the original code.

**Comment by hasansezertasan** [comment]
I did, can you check if it's all right? I'll publish a release when you confirm.

**Comment by primaryobjects** [comment]
Perfect, thank you!

**Comment by hasansezertasan** [comment]
Thank you for reaching out. I have just released 0.3.1.

**Comment by hasansezertasan** [comment]
Don't forget to give it a star ⭐!
